# Generated by Django 4.2.2 on 2023-10-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="myapp.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="userid",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
