# Generated by Django 4.2.2 on 2023-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_post_account_alter_account_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
