# Generated by Django 4.2.2 on 2023-10-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_post_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post", unique_together={("account", "title")},
        ),
    ]
